spring.datasource.url=jdbc:postgresql://ep-delicate-butterfly-ape3gj1i.c-7.us-east-1.aws.neon.tech/neondb?sslmode=require

spring.datasource.username=neondb_owner

spring.datasource.password=npg_i1LQOrdPGRg3

spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true

spring.datasource.hikari.maximum-pool-size=2