spring.application.name=Authentication and Authorization System
spring.datasource.url=jdbc:mysql://localhost:3306/auth_system
spring.datasource.username=root
spring.datasource.password=VEDANT24

spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true

server.port=8080